# Generated by Django 5.0.4 on 2024-05-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
