# Generated by Django 5.0.4 on 2024-05-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0003_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gt.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gt.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gt.size')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='gt.OrderItem', to='gt.product'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
