# Generated by Django 5.0.4 on 2024-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0004_orderitem_order_products_delete_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
