# Generated by Django 5.0.4 on 2024-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0005_product_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Unisex', max_length=10),
        ),
    ]
