# Generated by Django 5.0.4 on 2024-05-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0006_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
