# Generated by Django 5.0.4 on 2024-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt', '0007_remove_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
